---
- hosts: target1
  gather_facts: no
  become: true

  tasks:

    - name: Read secret file
      include_vars: "my-secret-information.yml"

    - name: Display superhero
      debug:
        msg: "The real identity of {{ secret.superhero }} is {{ secret.name }}"

